import { NextResponse } from 'next/server'

/**
 * Demo mode — returns a realistic pre-computed deviation report.
 * Represents a pulmonary fibrosis–like profile built from real HLCA biology.
 * All field names and values match the DeviationReport + BiologicalInterpretation
 * Pydantic schemas in app/models/schemas.py exactly.
  */
export async function POST() {
  const now = new Date().toISOString()

  const report = {
    sample_id: 'DEMO-IPF-001',
    analysed_at: now,
    model_built_at: '2025-05-01T00:00:00Z',
    overall_deviation_score: 0.74,
    summary:
      'Substantial deviation from healthy respiratory reference. Fibroblasts is expanded (severe, Z=+4.1). Gene deviations in COL1A1, FN1, MUC5B, SPP1. Extracellular matrix organisation pathway is markedly over-active (+2.31 log1p CP10K above healthy baseline).',
    healthy_reference_cells: 1305099,
    healthy_reference_donors: 268,
    safety_disclaimer:
      'RESEARCH USE ONLY — NOT A DIAGNOSTIC DEVICE. This output describes statistical deviations from a healthy reference model. It does not constitute a clinical diagnosis. All findings must be reviewed and interpreted by a qualified specialist.',

    cell_type_deviations: [
      {
        cell_type: 'AT2 (Alveolar Type II)',
        compartment: 'alveolar',
        estimated_fraction: 0.030,
        healthy_mean_fraction: 0.120,
        healthy_std_fraction: 0.035,
        z_score: -3.2,
        direction: 'depleted',
        magnitude: 'severe',
        interpretation: 'AT2 cells produce surfactant; depletion impairs gas exchange and alveolar repair.',
      },
      {
        cell_type: 'Fibroblasts',
        compartment: 'stromal',
        estimated_fraction: 0.220,
        healthy_mean_fraction: 0.070,
        healthy_std_fraction: 0.025,
        z_score: 4.1,
        direction: 'expanded',
        magnitude: 'severe',
        interpretation: 'Fibroblast expansion is a hallmark of fibrotic remodelling.',
      },
      {
        cell_type: 'Macrophages (alveolar)',
        compartment: 'immune',
        estimated_fraction: 0.190,
        healthy_mean_fraction: 0.120,
        healthy_std_fraction: 0.030,
        z_score: 2.8,
        direction: 'expanded',
        magnitude: 'moderate',
        interpretation: 'Alveolar macrophages maintain sterility and clear debris; shifts indicate immune activation.',
      },
      {
        cell_type: 'Club cells',
        compartment: 'airway',
        estimated_fraction: 0.030,
        healthy_mean_fraction: 0.060,
        healthy_std_fraction: 0.020,
        z_score: -2.1,
        direction: 'depleted',
        magnitude: 'moderate',
        interpretation: '',
      },
      {
        cell_type: 'AT1 (Alveolar Type I)',
        compartment: 'alveolar',
        estimated_fraction: 0.055,
        healthy_mean_fraction: 0.085,
        healthy_std_fraction: 0.028,
        z_score: -1.8,
        direction: 'depleted',
        magnitude: 'mild',
        interpretation: '',
      },
      {
        cell_type: 'Smooth muscle cells',
        compartment: 'stromal',
        estimated_fraction: 0.038,
        healthy_mean_fraction: 0.027,
        healthy_std_fraction: 0.012,
        z_score: 1.6,
        direction: 'expanded',
        magnitude: 'mild',
        interpretation: '',
      },
    ],

    gene_deviations: [
      {
        gene: 'COL1A1',
        z_score: 5.1,
        direction: 'elevated',
        magnitude: 'severe',
        sample_value: 4.21,
        healthy_mean: 0.38,
        healthy_std: 0.75,
        healthy_p5: 0.04,
        healthy_p95: 1.45,
      },
      {
        gene: 'FN1',
        z_score: 4.3,
        direction: 'elevated',
        magnitude: 'severe',
        sample_value: 3.84,
        healthy_mean: 0.71,
        healthy_std: 0.73,
        healthy_p5: 0.08,
        healthy_p95: 1.88,
      },
      {
        gene: 'SFTPC',
        z_score: -4.2,
        direction: 'suppressed',
        magnitude: 'severe',
        sample_value: 0.82,
        healthy_mean: 3.54,
        healthy_std: 0.65,
        healthy_p5: 2.40,
        healthy_p95: 4.65,
      },
      {
        gene: 'SFTPB',
        z_score: -3.8,
        direction: 'suppressed',
        magnitude: 'severe',
        sample_value: 0.91,
        healthy_mean: 3.22,
        healthy_std: 0.61,
        healthy_p5: 2.15,
        healthy_p95: 4.28,
      },
      {
        gene: 'MUC5B',
        z_score: 3.7,
        direction: 'elevated',
        magnitude: 'severe',
        sample_value: 2.94,
        healthy_mean: 0.55,
        healthy_std: 0.65,
        healthy_p5: 0.06,
        healthy_p95: 1.64,
      },
      {
        gene: 'SPP1',
        z_score: 3.2,
        direction: 'elevated',
        magnitude: 'severe',
        sample_value: 2.41,
        healthy_mean: 0.48,
        healthy_std: 0.60,
        healthy_p5: 0.05,
        healthy_p95: 1.45,
      },
      {
        gene: 'TGFB1',
        z_score: 2.9,
        direction: 'elevated',
        magnitude: 'moderate',
        sample_value: 1.92,
        healthy_mean: 0.61,
        healthy_std: 0.45,
        healthy_p5: 0.10,
        healthy_p95: 1.35,
      },
      {
        gene: 'AGER',
        z_score: -2.5,
        direction: 'suppressed',
        magnitude: 'moderate',
        sample_value: 0.61,
        healthy_mean: 2.18,
        healthy_std: 0.63,
        healthy_p5: 1.10,
        healthy_p95: 3.25,
      },
      {
        gene: 'ACTA2',
        z_score: 2.4,
        direction: 'elevated',
        magnitude: 'moderate',
        sample_value: 3.12,
        healthy_mean: 1.04,
        healthy_std: 0.87,
        healthy_p5: 0.14,
        healthy_p95: 2.62,
      },
      {
        gene: 'VEGFA',
        z_score: -2.1,
        direction: 'suppressed',
        magnitude: 'moderate',
        sample_value: 0.89,
        healthy_mean: 2.02,
        healthy_std: 0.54,
        healthy_p5: 1.05,
        healthy_p95: 2.95,
      },
    ],

    pathway_deviations: [
      {
        pathway: 'Extracellular matrix organisation',
        category: 'matrix_remodelling',
        direction: 'over-active',
        n_active_genes: 14,
        n_total_genes: 18,
        avg_expression: 3.42,
        trigger_baseline_expr: 0.74,
        deviation_from_baseline: 2.31,
        active_genes: ['COL1A1', 'FN1', 'COL3A1', 'TIMP1', 'MMP2', 'POSTN'],
        interpretation: 'Extracellular matrix organisation pathway is markedly over-active (+2.31 log1p CP10K above healthy baseline).',
      },
      {
        pathway: 'TGF-β / SMAD signalling',
        category: 'profibrotic_signalling',
        direction: 'over-active',
        n_active_genes: 9,
        n_total_genes: 12,
        avg_expression: 1.92,
        trigger_baseline_expr: 0.61,
        deviation_from_baseline: 1.87,
        active_genes: ['TGFB1', 'SMAD3', 'ACTA2', 'CTGF'],
        interpretation: 'TGF-β / SMAD signalling pathway is markedly over-active (+1.87 log1p CP10K above healthy baseline).',
      },
      {
        pathway: 'Surfactant metabolism',
        category: 'alveolar_function',
        direction: 'suppressed',
        n_active_genes: 4,
        n_total_genes: 11,
        avg_expression: 0.89,
        trigger_baseline_expr: 3.10,
        deviation_from_baseline: -2.14,
        active_genes: ['SFTPC', 'SFTPB', 'ABCA3'],
        interpretation: 'Surfactant metabolism pathway is markedly suppressed (−2.14 log1p CP10K below healthy baseline).',
      },
      {
        pathway: 'Inflammatory cytokine response',
        category: 'immune_activation',
        direction: 'over-active',
        n_active_genes: 11,
        n_total_genes: 15,
        avg_expression: 1.88,
        trigger_baseline_expr: 0.55,
        deviation_from_baseline: 1.44,
        active_genes: ['SPP1', 'IL6', 'CCL2', 'CXCL8'],
        interpretation: 'Inflammatory cytokine response pathway is moderately over-active (+1.44 log1p CP10K above healthy baseline).',
      },
      {
        pathway: 'Alveolar epithelial repair',
        category: 'regeneration',
        direction: 'suppressed',
        n_active_genes: 3,
        n_total_genes: 9,
        avg_expression: 1.22,
        trigger_baseline_expr: 2.95,
        deviation_from_baseline: -1.76,
        active_genes: ['KRT8', 'KRT18'],
        interpretation: 'Alveolar epithelial repair pathway is markedly suppressed (−1.76 log1p CP10K below healthy baseline).',
      },
      {
        pathway: 'Oxidative stress response',
        category: 'stress_response',
        direction: 'over-active',
        n_active_genes: 7,
        n_total_genes: 10,
        avg_expression: 1.62,
        trigger_baseline_expr: 0.48,
        deviation_from_baseline: 1.21,
        active_genes: ['HMOX1', 'GPX4', 'SOD2', 'NRF2'],
        interpretation: 'Oxidative stress response pathway is moderately over-active (+1.21 log1p CP10K above healthy baseline).',
      },
    ],
  }

  const interpretation = {
    sample_id: 'DEMO-IPF-001',
    interpreted_at: now,
    model_id: 'claude-opus-4-7',
    prompt_version: 'v6',
    overall_deviation_score: 0.74,
    stage: 'Established',
    overall_confidence: 'High',
    final_interpretation:
      'The deviation profile shows significant alveolar compartment disruption, with type II pneumocyte depletion (Z=−3.2, severe) and fibroblast expansion (Z=+4.1, severe) forming the dominant biological signal. The concurrent suppression of surfactant biosynthesis (−2.14 log1p CP10K from baseline) and activation of extracellular matrix organisation (+2.31 log1p CP10K from baseline) is consistent with progressive alveolar simplification. Elevated SPP1 (Z=+3.2), TGFB1 (Z=+2.9), and macrophage expansion (Z=+2.8) indicate active profibrotic signalling across multiple cell compartments.',
    biological_question:
      'Is the observed fibroblast expansion driving irreversible matrix deposition, or does residual AT2 regenerative capacity remain that could respond to antifibrotic intervention?',
    anomalous_findings: [
      'COL1A1 expression is 11× the healthy mean (Z=+5.1) — sample value 4.21 vs healthy range 0.04–1.45 (log1p CP10K)',
      'MUC5B elevation (Z=+3.7) co-occurring with AT2 depletion (Z=−3.2) suggests a bronchiolisation pattern',
      'Simultaneous loss of SFTPC (Z=−4.2) and AGER (Z=−2.5) indicates disruption of both AT2 and AT1 compartments',
    ],
    full_reasoning:
      'Step 1 — Cell type composition scored against donor reference (n=268 donors).\nAT2: estimated fraction 0.030 vs healthy mean 0.120 ± 0.035 → Z=−3.2 (severe depletion).\nFibroblasts: estimated fraction 0.220 vs healthy mean 0.070 ± 0.025 → Z=+4.1 (severe expansion).\nMacrophages (alveolar): 0.190 vs 0.120 ± 0.030 → Z=+2.8 (moderate expansion).\nClub cells: 0.030 vs 0.060 ± 0.020 → Z=−2.1 (moderate depletion).\n\nStep 2 — Gene-level Z-scores (threshold |Z| ≥ 2.0).\nCOL1A1: sample 4.21 vs healthy mean 0.38 ± 0.75, healthy range (p5–p95) 0.04–1.45 → Z=+5.1.\nFN1: sample 3.84 vs healthy mean 0.71 ± 0.73, range 0.08–1.88 → Z=+4.3.\nSFTPC: sample 0.82 vs healthy mean 3.54 ± 0.65, range 2.40–4.65 → Z=−4.2.\nSFTPB: sample 0.91 vs healthy mean 3.22 ± 0.61, range 2.15–4.28 → Z=−3.8.\n\nStep 3 — Pathway deviation from healthy baseline (threshold |Δ| ≥ 0.8 log1p CP10K).\nECM organisation: sample avg 3.42 vs baseline 0.74 → Δ=+2.31 (markedly over-active, 14/18 pathway genes present).\nTGF-β/SMAD: sample avg 1.92 vs baseline 0.61 → Δ=+1.87 (markedly over-active, 9/12 genes).\nSurfactant metabolism: sample avg 0.89 vs baseline 3.10 → Δ=−2.14 (markedly suppressed, 4/11 genes).\n\nStep 4 — Cross-validation.\nAll three dimensions (cell types, genes, pathways) converge on the same biology: fibrotic remodelling with AT2 loss and ECM expansion. No contradictory signals. Confidence: High.\n\nThis profile does not constitute a clinical diagnosis. Specialist review required.',
  }

  return NextResponse.json({ report, interpretation })
}
